In [1]:
from tictactoe import *

class QPlayer:
    
    EXPLORE = 0.10

    def __init__(self, explore=EXPLORE, verbose=False):
        self.q_table = np.zeros([3**9,9])
        self.explore = explore
        self.wins = 0
        self.losses = 0
        self.verbose = verbose
        
    def move(self, board, state):
        self.state = state
        self.action = np.argmax(self.q_table[state])
        if self.verbose:
            print(board)
            print(state,self.q_table[state])
        if np.random.random() < self.explore:
            self.action = board.sample()
        return self.action
    
    def set_verbose(self, v):
        self.verbose = v

    def update(self, board, state, reward):
        self.q_table[self.state][self.action] += reward
        if reward > 0:
            self.explore *= 0.999
            self.wins += 1
        if reward < 0:
            self.losses += 1

    def __str__(self):
        return str(np.sum(self.q_table)) + ' wins = ' + str(self.wins) + ' losses = ' + str(self.losses)

In [ ]:
q = QPlayer()
r = QPlayer()
b = Board(q,r)
for n in range(1000):
    b.play()
print(q)
print(r)
b = Board(r,q)
for n in range(1000):
    b.play()
print(q)
print(r)

q.set_verbose(True)
h = HumanPlayer()
b = Board(q,h)
while True:
    b.play(verbose=True)


-1670.0 wins = 522 losses = 221
-3090.0 wins = 2 losses = 779
-4805.0 wins = 526 losses = 1029
-4405.0 wins = 551 losses = 969
========= NEW GAME =======================
------------------------------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
------------------------------------------

9841 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
------------------------------------------
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
------------------------------------------

8
------------------------------------------
[[ 1.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0. -1.]]
------------------------------------------

------------------------------------------
[[ 1.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0. -1.]]
------------------------------------------

3281 [-10.   0.   0.   0.   0.   0.   0.   0.   0.]
------------------------------------------
[[ 1.  1.  0.]
 [ 0.  0.  0.]
 [ 0.  0. -1.]]
------------------------------------------

8
Human player received a reward -10
========= NEW GAME =======================
---------------

In [ ]:
print(q,r)

In [ ]:
q.set_verbose(True)
h = HumanPlayer()
b = Board(q,h)
while True:
    b.play(verbose=True)

In [ ]:
q = QPlayer()
r = QPlayer()
b = Board(q,r)
for n in range(10000):
    b.play()
print(q)
print(r)
b = Board(r,q)
for n in range(10000):
    b.play()
print(q)
print(r)

In [ ]:
h = HumanPlayer()
b = Board(q,h)
while True:
    b.play(verbose=True)

In [ ]:
q0 = QPlayer()
q1 = QPlayer()

b = Board(q0,q1)
for i in range(10000):
    b.play()
    
print(q0)
print(q1)

b = Board(q1,q0)
for i in range(10000):
    b.play()
    
print(q0)
print(q1)


In [ ]:
h = HumanPlayer()
b = Board(q1,h)
for n in range(10):
    b.play(verbose=True)

In [ ]:
h = HumanPlayer()
b = Board(q1,h)
for n in range(10):
    b.play(verbose=True)