The board is a 3x3 array; x's are represented as 1's, and o's are -1's; a blank square is a zero.

In [4]:
import numpy as np

board = np.zeros([3,3])

board

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

To identify winning conditions, takes sums along various axes and look for totals of +3 or -3:

In [70]:
# make a test array to figure out how np.sum() works...

test_board = np.array([[1,2,3],[5,5,5],[3,2,1]])
test_board

array([[1, 2, 3],
       [5, 5, 5],
       [3, 2, 1]])

In [71]:
# this call returns the sum of each column
np.sum(test_board, 0)

array([9, 9, 9])

In [72]:
# this call returns the sum of each row
np.sum(test_board, 1)

array([ 6, 15,  6])

In [73]:
# this call sums the first diagonal
test_board.trace(0)

7

In [74]:
# and for the second diagonal, flip the matrix
np.flip(test_board,0).trace(0)

11

...to find out who wins:

In [76]:
# returns the max and min of sum of each axis + each diagonal
def max_min(board):
    col_sum = np.sum(board,0)
    row_sum = np.sum(board,1)
    maxs = np.maximum(col_sum,row_sum)
    mins = np.minimum(col_sum,row_sum)
    diag0 = board.trace(0)
    diag1 = np.flip(board,0).trace(0)
    return max(max(maxs), diag0, diag1), min(min(mins), diag0, diag1)

# returns winner (if one player had won), else None
def winner(board):
    x,o = max_min(board)
    if x == 3:
        return 'x'
    elif o == -3:
        return 'o'
    else:
        return None

In [77]:
board = np.array([[1,-1,0],[-1,1,0],[-1,0,1]])
print(board)
print(winner(board),'wins')

[[ 1 -1  0]
 [-1  1  0]
 [-1  0  1]]
x wins


In [78]:
board = np.array([[-1,0,1],[0,-1,-1],[1,1,-1]])
print(board)
print(winner(board),'wins')

[[-1  0  1]
 [ 0 -1 -1]
 [ 1  1 -1]]
o wins


In [79]:
board = np.array([[1,1,1],[-1,-1,0],[0,0,-1]])
print(board)
print(winner(board),'wins')

[[ 1  1  1]
 [-1 -1  0]
 [ 0  0 -1]]
x wins


In [80]:
board = np.array([[1,0,-1],[1,0,-1],[0,1,-1]])
print(board)
print(winner(board),'wins')

[[ 1  0 -1]
 [ 1  0 -1]
 [ 0  1 -1]]
o wins
